### ISSUE TITLE
cannot install psycodict

### ISSUE THREAD

**Issue by stmar89** [roed314/psycodict#26]
Using pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
Defaulting to user installation because normal site-packages is not writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-bw66zen4
Created temporary directory: /tmp/pip-req-tracker-0j3mvnsh
Initialized build tracking at /tmp/pip-req-tracker-0j3mvnsh
Created build tracker: /tmp/pip-req-tracker-0j3mvnsh
Entered build tracker: /tmp/pip-req-tracker-0j3mvnsh
Created temporary directory: /tmp/pip-install-53ez2wyh
Collecting git+https://github.com/roed314/psycodict.git
  Created temporary directory: /tmp/pip-req-build-2h7pbi_8
  Cloning https://github.com/roed314/psycodict.git to /tmp/pip-req-build-2h7pbi_8
  Running command git version
  git version 2.34.1
  Running command git clone --filter=blob:none --verbose --progress https://github.com/roed314/psycodict.git /tmp/pip-req-build-2h7pbi_8
  Cloning into '/tmp/pip-req-build-2h7pbi_8'...
  POST git-upload-pack (175 bytes)
  POST git-upload-pack (522 bytes)

....

  Running command git rev-parse HEAD
  e00011fc4fc42269ff9051f86e0679756767a322
  Resolved https://github.com/roed314/psycodict.git to commit e00011fc4fc42269ff9051f86e0679756767a322
  Added git+https://github.com/roed314/psycodict.git to build tracker '/tmp/pip-req-tracker-0j3mvnsh'
  Created temporary directory: /tmp/pip-build-env-_thyc6ii
  Created temporary directory: /tmp/pip-standalone-pip-swzflx8y
  Running command pip subprocess to install build dependencies
  Using pip 22.0.2 from /tmp/pip-standalone-pip-swzflx8y/__env_pip__.zip/pip (python 3.10)
  Collecting setuptools
    Using cached setuptools-75.4.0-py3-none-any.whl (1.2 MB)
  Collecting wheel
    Using cached wheel-0.45.0-py3-none-any.whl (72 kB)
  Installing collected packages: wheel, setuptools
    Creating /tmp/pip-build-env-_thyc6ii/overlay/local/bin
    changing mode of /tmp/pip-build-env-_thyc6ii/overlay/local/bin/wheel to 755
  Successfully installed setuptools-75.4.0 wheel-0.45.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  running egg_info
  creating UNKNOWN.egg-info
  writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
  writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
  Getting requirements to build wheel ... done
  Created temporary directory: /tmp/pip-modern-metadata-enadux6t
  Running command Preparing metadata (pyproject.toml)
  running dist_info
  creating /tmp/pip-modern-metadata-enadux6t/UNKNOWN.egg-info
  writing manifest file '/tmp/pip-modern-metadata-enadux6t/UNKNOWN.egg-info/SOURCES.txt'
  writing manifest file '/tmp/pip-modern-metadata-enadux6t/UNKNOWN.egg-info/SOURCES.txt'
  Preparing metadata (pyproject.toml) ... done
  Source in /tmp/pip-req-build-2h7pbi_8 has version 0.0.0, which satisfies requirement UNKNOWN==0.0.0 from git+https://github.com/roed314/psycodict.git
  Removed UNKNOWN==0.0.0 from git+https://github.com/roed314/psycodict.git from build tracker '/tmp/pip-req-tracker-0j3mvnsh'
Created temporary directory: /tmp/pip-unpack-0w13bb9a
Removed build tracker: '/tmp/pip-req-tracker-0j3mvnsh'

**Comment by edgarcosta** [comment]
the issue was an old version of pip
